/**
 * AUTO-GENERATED by scripts/generate-gcse-integration.ts — do not edit.
 * Source: data/gcse-import/*.csv
 */
import type { GcseNovaIntegration } from '@/lib/gcseImport/bridgeNova';
import generatedJson from '@/lib/gcseImport/generatedIntegration.json';

export const generatedGcse: GcseNovaIntegration = generatedJson as GcseNovaIntegration;
export default generatedGcse;
