/**
 * GCSE English Language & English Literature Objectives
 * AQA & Pearson Edexcel - Skills-based (Language) and Text-based (Literature)
 */

import type { Objective } from '../types';

function obj(base: Omit<Objective, 'examBoards'> & { examBoards?: ('AQA' | 'Pearson Edexcel')[] }): Objective {
  return {
    ...base,
    examBoards: base.examBoards ?? ['AQA', 'Pearson Edexcel'],
  };
}

// ============================================
// ENGLISH LANGUAGE - Skills-based (transferable)
// ============================================

export const englishLanguageObjectives: Objective[] = [
  // Reading
  obj({
    id: 'englang-read-001',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-retrieval',
    topicTitle: 'Retrieval of explicit information',
    title: 'Identifying Explicit Information',
    description: 'Find and retrieve explicit information and ideas from 19th-, 20th-, and 21st-century texts.',
    yearMin: 7,
    yearMax: 11,
    difficulty: 1,
    prerequisites: [],
    keywords: ['explicit', 'find', 'retrieve', 'information'],
  }),
  obj({
    id: 'eng-read-002',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-inference',
    topicTitle: 'Inference',
    title: 'Making Inferences',
    description: 'Make inferences and deduce meaning from texts using evidence.',
    yearMin: 7,
    yearMax: 11,
    difficulty: 2,
    prerequisites: ['englang-read-001'],
    keywords: ['inference', 'deduce', 'imply', 'suggest'],
  }),
  obj({
    id: 'eng-read-003',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-language',
    topicTitle: 'Language analysis',
    title: 'Analysing Word Choice',
    description: 'Analyse how writers use specific words and phrases for effect.',
    yearMin: 8,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['eng-read-002'],
    keywords: ['word choice', 'connotation', 'effect', 'language'],
  }),
  obj({
    id: 'englang-read-004',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-structure',
    topicTitle: 'Structure analysis',
    title: 'Analysing Sentence Structure',
    description: 'Analyse how sentence structures contribute to meaning and effect.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['eng-read-003'],
    keywords: ['sentence structure', 'syntax', 'short sentences', 'complex sentences'],
  }),
  obj({
    id: 'englang-read-005',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-structure',
    topicTitle: 'Structure analysis',
    title: 'Analysing Text Structure',
    description: 'Analyse how writers structure whole texts for effect (openings, endings, shifts).',
    yearMin: 9,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englang-read-004'],
    keywords: ['structure', 'opening', 'ending', 'narrative arc'],
  }),
  obj({
    id: 'englang-read-006',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-comparing',
    topicTitle: 'Comparing writers\' ideas and perspectives',
    title: 'Comparing Writers\' Ideas and Perspectives',
    description: 'Compare how writers convey ideas and perspectives across two texts.',
    yearMin: 10,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englang-read-003', 'englang-read-001'],
    keywords: ['compare', 'perspective', 'viewpoint', 'ideas'],
  }),
  obj({
    id: 'englang-read-007',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-viewpoint',
    topicTitle: 'Analysing viewpoint, tone, and methods',
    title: 'Evaluating Texts Critically',
    description: 'Evaluate texts critically and support with evidence.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englang-read-005'],
    keywords: ['evaluate', 'critically', 'evidence', 'judgement'],
  }),
  obj({
    id: 'englang-read-008',
    subject: 'English Language',
    strand: 'Reading',
    topicId: 'read-summary',
    topicTitle: 'Summary and synthesis',
    title: 'Summary and Synthesis',
    description: 'Summarise and synthesise information from texts.',
    yearMin: 8,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['englang-read-001'],
    keywords: ['summary', 'synthesise', 'key points'],
  }),

  // Writing
  obj({
    id: 'eng-writ-001',
    subject: 'English Language',
    strand: 'Writing',
    topicId: 'writ-transactional',
    topicTitle: 'Transactional writing',
    title: 'Transactional Writing',
    description: 'Write for a purpose: letters, articles, speeches, leaflets.',
    yearMin: 8,
    yearMax: 11,
    difficulty: 3,
    prerequisites: [],
    keywords: ['transactional', 'audience', 'purpose', 'form'],
  }),
  obj({
    id: 'englang-writ-002',
    subject: 'English Language',
    strand: 'Writing',
    topicId: 'writ-descriptive',
    topicTitle: 'Descriptive writing',
    title: 'Descriptive Writing',
    description: 'Write descriptively using sensory detail and imagery.',
    yearMin: 7,
    yearMax: 11,
    difficulty: 2,
    prerequisites: [],
    keywords: ['descriptive', 'imagery', 'sensory', 'detail'],
  }),
  obj({
    id: 'englang-writ-003',
    subject: 'English Language',
    strand: 'Writing',
    topicId: 'writ-narrative',
    topicTitle: 'Narrative writing',
    title: 'Narrative Writing',
    description: 'Write narratives with effective structure and characterisation.',
    yearMin: 7,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['englang-writ-002'],
    keywords: ['narrative', 'story', 'structure', 'character'],
  }),
  obj({
    id: 'englang-writ-004',
    subject: 'English Language',
    strand: 'Writing',
    topicId: 'writ-audience',
    topicTitle: 'Audience, purpose, and form',
    title: 'Audience, Purpose, and Form',
    description: 'Adapt writing for audience, purpose, and form.',
    yearMin: 8,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['englang-writ-001'],
    keywords: ['audience', 'purpose', 'form', 'register'],
  }),

  // SPaG
  obj({
    id: 'englang-spag-001',
    subject: 'English Language',
    strand: 'SPaG and Vocabulary',
    topicId: 'spag-sentences',
    topicTitle: 'Sentence control, punctuation, grammar, vocabulary, spelling',
    title: 'Sentence Control and Punctuation',
    description: 'Use varied sentence structures and accurate punctuation.',
    yearMin: 7,
    yearMax: 11,
    difficulty: 2,
    prerequisites: [],
    keywords: ['sentence', 'punctuation', 'grammar'],
  }),
  obj({
    id: 'englang-spag-002',
    subject: 'English Language',
    strand: 'SPaG and Vocabulary',
    topicId: 'spag-editing',
    topicTitle: 'Editing and improving writing',
    title: 'Editing and Improving Writing',
    description: 'Edit and improve writing for clarity and impact.',
    yearMin: 8,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['englang-spag-001'],
    keywords: ['edit', 'improve', 'proofread', 'redraft'],
  }),
];

// ============================================
// ENGLISH LITERATURE - Text families & skills
// ============================================

export const englishLiteratureObjectives: Objective[] = [
  // Shakespeare
  obj({
    id: 'englit-shake-001',
    subject: 'English Literature',
    strand: 'Shakespeare',
    topicId: 'lit-shakespeare',
    topicTitle: 'Shakespeare study',
    title: 'Shakespeare: Context and Themes',
    description: 'Understand Shakespeare\'s context and key themes in the set play.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: [],
    keywords: ['Shakespeare', 'context', 'theme', 'Elizabethan'],
  }),
  obj({
    id: 'englit-shake-002',
    subject: 'English Literature',
    strand: 'Shakespeare',
    topicId: 'lit-shakespeare',
    topicTitle: 'Shakespeare study',
    title: 'Shakespeare: Character Analysis',
    description: 'Analyse how Shakespeare presents characters through language and action.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['englit-shake-001'],
    keywords: ['character', 'Shakespeare', 'language', 'motivation'],
  }),
  obj({
    id: 'englit-shake-003',
    subject: 'English Literature',
    strand: 'Shakespeare',
    topicId: 'lit-shakespeare',
    topicTitle: 'Shakespeare study',
    title: 'Shakespeare: Quotation Knowledge',
    description: 'Recall and analyse key quotations from the set play.',
    yearMin: 10,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englit-shake-002'],
    keywords: ['quotation', 'recall', 'analysis'],
  }),

  // 19th-century novel
  obj({
    id: 'englit-19c-001',
    subject: 'English Literature',
    strand: '19th-century novel',
    topicId: 'lit-19c',
    topicTitle: '19th-century novel study',
    title: '19th-Century Novel: Context and Themes',
    description: 'Understand Victorian context and key themes in the set novel.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: [],
    keywords: ['Victorian', 'context', 'theme', 'novel'],
  }),
  obj({
    id: 'englit-19c-002',
    subject: 'English Literature',
    strand: '19th-century novel',
    topicId: 'lit-19c',
    topicTitle: '19th-century novel study',
    title: '19th-Century Novel: Language and Structure',
    description: 'Analyse language, form, and structure in the set novel.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englit-19c-001'],
    keywords: ['language', 'structure', 'narrative', 'analysis'],
  }),

  // Modern prose/drama
  obj({
    id: 'englit-mod-001',
    subject: 'English Literature',
    strand: 'Modern prose/drama',
    topicId: 'lit-modern',
    topicTitle: 'Modern prose/drama study',
    title: 'Modern Prose/Drama: Themes and Context',
    description: 'Understand context and themes in modern prose or drama.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: [],
    keywords: ['modern', 'context', 'theme', 'prose', 'drama'],
  }),

  // Poetry anthology
  obj({
    id: 'englit-poetry-001',
    subject: 'English Literature',
    strand: 'Poetry anthology',
    topicId: 'lit-poetry',
    topicTitle: 'Poetry anthology study',
    title: 'Poetry: Language and Form Analysis',
    description: 'Analyse language, form, and structure in anthology poems.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: [],
    keywords: ['poetry', 'form', 'structure', 'language'],
  }),
  obj({
    id: 'englit-poetry-002',
    subject: 'English Literature',
    strand: 'Poetry anthology',
    topicId: 'lit-poetry',
    topicTitle: 'Poetry anthology study',
    title: 'Poetry: Comparison',
    description: 'Compare poems from the anthology.',
    yearMin: 10,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englit-poetry-001'],
    keywords: ['compare', 'poetry', 'similarities', 'differences'],
  }),

  // Unseen poetry
  obj({
    id: 'englit-unseen-001',
    subject: 'English Literature',
    strand: 'Unseen poetry',
    topicId: 'lit-unseen',
    topicTitle: 'Unseen poetry',
    title: 'Unseen Poetry: Analysis',
    description: 'Analyse an unseen poem for language, form, and meaning.',
    yearMin: 10,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englit-poetry-001'],
    keywords: ['unseen', 'poetry', 'analysis'],
  }),
  obj({
    id: 'englit-unseen-002',
    subject: 'English Literature',
    strand: 'Unseen poetry',
    topicId: 'lit-unseen',
    topicTitle: 'Unseen poetry',
    title: 'Unseen Poetry: Comparison',
    description: 'Compare two unseen poems.',
    yearMin: 10,
    yearMax: 11,
    difficulty: 5,
    prerequisites: ['englit-unseen-001', 'englit-poetry-002'],
    keywords: ['unseen', 'compare', 'poetry'],
  }),

  // Essay skills
  obj({
    id: 'englit-essay-001',
    subject: 'English Literature',
    strand: 'Essay skills',
    topicId: 'lit-essay',
    topicTitle: 'Essay planning and timed literary response',
    title: 'Essay Planning and Structure',
    description: 'Plan and structure a literary essay effectively.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: [],
    keywords: ['essay', 'plan', 'structure', 'PEE'],
  }),
  obj({
    id: 'englit-essay-002',
    subject: 'English Literature',
    strand: 'Essay skills',
    topicId: 'lit-essay',
    topicTitle: 'Essay planning and timed literary response',
    title: 'Timed Literary Response',
    description: 'Write a timed literary response under exam conditions.',
    yearMin: 10,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['englit-essay-001'],
    keywords: ['timed', 'exam', 'response'],
  }),
];
