/**
 * GCSE Curriculum Objectives - AQA & Pearson Edexcel
 * Structure: Subject → Exam Board → Tier → Strand → Topic → Objective
 */

import type { Objective } from '../types';
import type { ExamBoard } from '../curriculumTypes';

// Helper to create objective with exam board tags
function obj(
  base: Omit<Objective, 'examBoards'> & { examBoards?: ExamBoard[] }
): Objective {
  return {
    ...base,
    examBoards: base.examBoards ?? ['AQA', 'Pearson Edexcel'],
  };
}

// ============================================
// MATHS OBJECTIVES - Full GCSE (AQA & Edexcel)
// ============================================

export const mathsObjectivesAqaEdexcel: Objective[] = [
  // NUMBER
  obj({
    id: 'math-num-001',
    subject: 'Mathematics',
    strand: 'Number',
    topicId: 'num-bidmas',
    topicTitle: 'BIDMAS / Order of operations',
    title: 'Order of Operations (BIDMAS)',
    description: 'Apply the correct order of operations including brackets, indices, division, multiplication, addition and subtraction.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: [],
    keywords: ['BIDMAS', 'BODMAS', 'order of operations', 'brackets'],
  }),
  obj({
    id: 'math-num-002',
    subject: 'Mathematics',
    strand: 'Number',
    topicId: 'num-factors',
    topicTitle: 'Factors, multiples, primes, HCF, LCM',
    title: 'Prime Factorisation',
    description: 'Express a number as a product of its prime factors using index notation. Find HCF and LCM.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: ['math-num-001'],
    keywords: ['prime', 'factors', 'HCF', 'LCM', 'factor tree'],
  }),
  obj({
    id: 'math-num-003',
    subject: 'Mathematics',
    strand: 'Number',
    topicId: 'num-fdp',
    topicTitle: 'Integers, decimals, fractions, percentages',
    title: 'Fractions, Decimals and Percentages',
    description: 'Convert between fractions, decimals and percentages. Order and compare them.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: [],
    keywords: ['fraction', 'decimal', 'percentage', 'convert'],
  }),
  obj({
    id: 'math-num-004',
    subject: 'Mathematics',
    strand: 'Number',
    topicId: 'num-percentages',
    topicTitle: 'Percentage change and reverse',
    title: 'Percentage Change',
    description: 'Calculate percentage increase and decrease. Find the original value after a percentage change.',
    yearMin: 8,
    yearMax: 10,
    difficulty: 3,
    prerequisites: ['math-num-003'],
    keywords: ['percentage increase', 'percentage decrease', 'reverse percentage'],
  }),
  obj({
    id: 'math-num-005',
    subject: 'Mathematics',
    strand: 'Number',
    topicId: 'num-indices',
    topicTitle: 'Indices, roots, standard form, surds',
    title: 'Laws of Indices',
    description: 'Use and apply the laws of indices for multiplication, division and powers of powers.',
    yearMin: 8,
    yearMax: 11,
    tier: 'Higher',
    difficulty: 3,
    prerequisites: ['math-num-001'],
    keywords: ['indices', 'powers', 'exponents', 'index laws'],
  }),
  obj({
    id: 'math-num-006',
    subject: 'Mathematics',
    strand: 'Number',
    topicId: 'num-standard-form',
    topicTitle: 'Standard form',
    title: 'Standard Form',
    description: 'Convert between ordinary numbers and standard form. Calculate with numbers in standard form.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-num-005'],
    keywords: ['standard form', 'scientific notation', 'powers of 10'],
  }),
  obj({
    id: 'math-num-007',
    subject: 'Mathematics',
    strand: 'Number',
    topicId: 'num-place-value',
    topicTitle: 'Place value, rounding, estimation, bounds',
    title: 'Bounds and Error Intervals',
    description: 'Calculate upper and lower bounds. Write error intervals.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-num-003'],
    keywords: ['bounds', 'rounding', 'error interval'],
  }),

  // ALGEBRA
  obj({
    id: 'math-alg-001',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-expressions',
    topicTitle: 'Algebraic expressions, substitution, simplifying',
    title: 'Simplifying Expressions',
    description: 'Collect like terms and simplify algebraic expressions.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 1,
    prerequisites: [],
    keywords: ['simplify', 'like terms', 'expressions', 'algebra'],
  }),
  obj({
    id: 'math-alg-002',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-expanding',
    topicTitle: 'Expanding and factorising',
    title: 'Expanding Single Brackets',
    description: 'Expand expressions with a single bracket by multiplying each term inside.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: ['math-alg-001'],
    keywords: ['expand', 'brackets', 'multiply', 'distribute'],
  }),
  obj({
    id: 'math-alg-003',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-expanding',
    topicTitle: 'Expanding and factorising',
    title: 'Expanding Double Brackets',
    description: 'Expand and simplify expressions with two brackets (FOIL method).',
    yearMin: 8,
    yearMax: 10,
    difficulty: 3,
    prerequisites: ['math-alg-002'],
    keywords: ['expand', 'double brackets', 'FOIL', 'quadratic'],
  }),
  obj({
    id: 'math-alg-004',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-expanding',
    topicTitle: 'Expanding and factorising',
    title: 'Factorising into Single Brackets',
    description: 'Factorise expressions by taking out a common factor.',
    yearMin: 8,
    yearMax: 10,
    difficulty: 2,
    prerequisites: ['math-alg-002'],
    keywords: ['factorise', 'common factor', 'HCF'],
  }),
  obj({
    id: 'math-alg-005',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-quadratics',
    topicTitle: 'Quadratic graphs and solving',
    title: 'Factorising Quadratics (a=1)',
    description: 'Factorise quadratic expressions of the form x² + bx + c into two brackets.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-alg-003', 'math-alg-004'],
    keywords: ['factorise', 'quadratic', 'brackets'],
  }),
  obj({
    id: 'math-alg-006',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-linear',
    topicTitle: 'Linear equations and inequalities',
    title: 'Solving Linear Equations',
    description: 'Solve equations with unknowns on one or both sides.',
    yearMin: 7,
    yearMax: 10,
    difficulty: 2,
    prerequisites: ['math-alg-001'],
    keywords: ['solve', 'equation', 'linear', 'unknown'],
  }),
  obj({
    id: 'math-alg-007',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-quadratics',
    topicTitle: 'Quadratic graphs and solving',
    title: 'Solving Quadratic Equations by Factorising',
    description: 'Solve quadratic equations by factorising and finding the roots.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['math-alg-005', 'math-alg-006'],
    keywords: ['quadratic', 'factorise', 'roots', 'solve'],
  }),
  obj({
    id: 'math-alg-008',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-quadratics',
    topicTitle: 'Quadratic graphs and solving',
    title: 'The Quadratic Formula',
    description: 'Use the quadratic formula x = (-b ± √(b²-4ac)) / 2a to solve quadratic equations.',
    yearMin: 10,
    yearMax: 11,
    tier: 'Higher',
    difficulty: 4,
    prerequisites: ['math-alg-007'],
    keywords: ['quadratic formula', 'discriminant', 'solve'],
  }),
  obj({
    id: 'math-alg-009',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-graphs',
    topicTitle: 'Straight-line graphs and coordinates',
    title: 'Straight Line Graphs (y = mx + c)',
    description: 'Plot and interpret straight line graphs. Find gradient and y-intercept.',
    yearMin: 8,
    yearMax: 10,
    difficulty: 3,
    prerequisites: ['math-alg-006'],
    keywords: ['gradient', 'y-intercept', 'linear graph', 'slope'],
  }),
  obj({
    id: 'math-alg-010',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-simultaneous',
    topicTitle: 'Simultaneous equations',
    title: 'Simultaneous Equations',
    description: 'Solve pairs of linear simultaneous equations algebraically.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['math-alg-006', 'math-alg-009'],
    keywords: ['simultaneous', 'elimination', 'substitution'],
  }),
  obj({
    id: 'math-alg-011',
    subject: 'Mathematics',
    strand: 'Algebra',
    topicId: 'alg-sequences',
    topicTitle: 'Sequences',
    title: 'Linear and Quadratic Sequences',
    description: 'Find the nth term of linear and quadratic sequences.',
    yearMin: 8,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-alg-001'],
    keywords: ['sequence', 'nth term', 'linear', 'quadratic'],
  }),

  // GEOMETRY AND MEASURES
  obj({
    id: 'math-geo-001',
    subject: 'Mathematics',
    strand: 'Geometry and Measures',
    topicId: 'geo-angles',
    topicTitle: 'Angle rules',
    title: 'Angle Facts',
    description: 'Use angle facts including angles on a straight line, around a point, and vertically opposite angles.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: [],
    keywords: ['angles', 'straight line', 'vertically opposite'],
  }),
  obj({
    id: 'math-geo-002',
    subject: 'Mathematics',
    strand: 'Geometry and Measures',
    topicId: 'geo-angles',
    topicTitle: 'Angle rules',
    title: 'Angles in Triangles and Quadrilaterals',
    description: 'Calculate missing angles in triangles and quadrilaterals.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: ['math-geo-001'],
    keywords: ['triangle', 'quadrilateral', 'interior angles'],
  }),
  obj({
    id: 'math-geo-003',
    subject: 'Mathematics',
    strand: 'Geometry and Measures',
    topicId: 'geo-pythagoras',
    topicTitle: 'Pythagoras',
    title: 'Pythagoras Theorem',
    description: 'Use Pythagoras theorem a² + b² = c² to find missing sides in right-angled triangles.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-geo-002'],
    keywords: ['Pythagoras', 'hypotenuse', 'right-angled triangle'],
  }),
  obj({
    id: 'math-geo-004',
    subject: 'Mathematics',
    strand: 'Geometry and Measures',
    topicId: 'geo-trig',
    topicTitle: 'Trigonometry',
    title: 'Trigonometry (SOHCAHTOA)',
    description: 'Use sine, cosine and tangent ratios to find missing sides and angles.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 4,
    prerequisites: ['math-geo-003'],
    keywords: ['trigonometry', 'sin', 'cos', 'tan', 'SOHCAHTOA'],
  }),
  obj({
    id: 'math-geo-005',
    subject: 'Mathematics',
    strand: 'Geometry and Measures',
    topicId: 'geo-area',
    topicTitle: 'Area, perimeter, volume, surface area',
    title: 'Area and Perimeter',
    description: 'Calculate area and perimeter of rectangles, triangles, parallelograms and trapeziums.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: [],
    keywords: ['area', 'perimeter', 'rectangle', 'triangle'],
  }),
  obj({
    id: 'math-geo-006',
    subject: 'Mathematics',
    strand: 'Geometry and Measures',
    topicId: 'geo-circles',
    topicTitle: 'Circles',
    title: 'Circles: Circumference and Area',
    description: 'Calculate the circumference and area of circles using C = πd and A = πr².',
    yearMin: 8,
    yearMax: 10,
    difficulty: 3,
    prerequisites: ['math-geo-005'],
    keywords: ['circle', 'circumference', 'area', 'pi', 'radius', 'diameter'],
  }),
  obj({
    id: 'math-geo-007',
    subject: 'Mathematics',
    strand: 'Geometry and Measures',
    topicId: 'geo-transformations',
    topicTitle: 'Transformations and constructions',
    title: 'Reflections and Rotations',
    description: 'Describe and perform reflections and rotations.',
    yearMin: 8,
    yearMax: 10,
    difficulty: 3,
    prerequisites: ['math-geo-001'],
    keywords: ['reflection', 'rotation', 'transformation'],
  }),

  // RATIO, PROPORTION AND RATES OF CHANGE
  obj({
    id: 'math-rat-001',
    subject: 'Mathematics',
    strand: 'Ratio, Proportion and Rates of Change',
    topicId: 'rat-ratio',
    topicTitle: 'Ratio, proportion, direct/inverse proportion',
    title: 'Simplifying Ratios',
    description: 'Write ratios in their simplest form and as 1:n or n:1.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: [],
    keywords: ['ratio', 'simplify', 'equivalent'],
  }),
  obj({
    id: 'math-rat-002',
    subject: 'Mathematics',
    strand: 'Ratio, Proportion and Rates of Change',
    topicId: 'rat-ratio',
    topicTitle: 'Ratio, proportion, direct/inverse proportion',
    title: 'Dividing in a Given Ratio',
    description: 'Divide a quantity in a given ratio.',
    yearMin: 8,
    yearMax: 10,
    difficulty: 2,
    prerequisites: ['math-rat-001'],
    keywords: ['ratio', 'divide', 'share', 'proportion'],
  }),
  obj({
    id: 'math-rat-003',
    subject: 'Mathematics',
    strand: 'Ratio, Proportion and Rates of Change',
    topicId: 'rat-rates',
    topicTitle: 'Rates, unit conversions, compound measures',
    title: 'Direct Proportion',
    description: 'Solve problems involving direct proportion and the relationship y = kx.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-rat-002'],
    keywords: ['direct proportion', 'constant of proportionality'],
  }),

  // STATISTICS
  obj({
    id: 'math-sta-001',
    subject: 'Mathematics',
    strand: 'Statistics',
    topicId: 'sta-averages',
    topicTitle: 'Averages, range, cumulative frequency, histograms, box plots',
    title: 'Averages: Mean, Median, Mode, Range',
    description: 'Calculate and interpret mean, median, mode and range for a data set.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: [],
    keywords: ['mean', 'median', 'mode', 'range', 'average'],
  }),
  obj({
    id: 'math-sta-002',
    subject: 'Mathematics',
    strand: 'Statistics',
    topicId: 'sta-averages',
    topicTitle: 'Averages, range, cumulative frequency, histograms, box plots',
    title: 'Averages from Frequency Tables',
    description: 'Calculate mean from frequency tables and grouped frequency tables.',
    yearMin: 8,
    yearMax: 10,
    difficulty: 3,
    prerequisites: ['math-sta-001'],
    keywords: ['frequency table', 'grouped data', 'estimated mean'],
  }),
  obj({
    id: 'math-sta-003',
    subject: 'Mathematics',
    strand: 'Statistics',
    topicId: 'sta-scatter',
    topicTitle: 'Scatter graphs and interpretation',
    title: 'Scatter Graphs and Correlation',
    description: 'Plot and interpret scatter graphs. Describe correlation.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-sta-001'],
    keywords: ['scatter', 'correlation', 'line of best fit'],
  }),

  // PROBABILITY
  obj({
    id: 'math-pro-001',
    subject: 'Mathematics',
    strand: 'Probability',
    topicId: 'pro-rules',
    topicTitle: 'Probability rules and tree diagrams',
    title: 'Basic Probability',
    description: 'Calculate theoretical probability of single events. Express as fractions, decimals or percentages.',
    yearMin: 7,
    yearMax: 9,
    difficulty: 2,
    prerequisites: ['math-num-003'],
    keywords: ['probability', 'likely', 'certain', 'impossible'],
  }),
  obj({
    id: 'math-pro-002',
    subject: 'Mathematics',
    strand: 'Probability',
    topicId: 'pro-rules',
    topicTitle: 'Probability rules and tree diagrams',
    title: 'Probability Trees',
    description: 'Use probability tree diagrams for combined events.',
    yearMin: 9,
    yearMax: 11,
    difficulty: 3,
    prerequisites: ['math-pro-001'],
    keywords: ['probability tree', 'combined events', 'branches'],
  }),
];
