/**
 * Regenerates lib/gcseImport/generatedIntegration.json + .ts from data/gcse-import/*.csv
 * Run: npx tsx scripts/generate-gcse-integration.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { buildGcseNovaIntegration } from '../lib/gcseImport/bridgeNova';

const root = join(__dirname, '..');
const dir = join(root, 'data', 'gcse-import');

const integration = buildGcseNovaIntegration('org_ttutors', 'teacher_zain', {
  studentsMaster: read(join(dir, 'gcse_students_master.csv')),
  billingGroups: read(join(dir, 'gcse_billing_groups.csv')),
  attendance: read(join(dir, 'gcse_attendance_mar_apr_2026.csv')),
  closures: read(join(dir, 'gcse_class_closures.csv')),
  monthlyBilling: read(join(dir, 'gcse_monthly_billing_starter_mar_apr_2026.csv')),
});

const jsonPath = join(root, 'lib', 'gcseImport', 'generatedIntegration.json');
writeFileSync(jsonPath, JSON.stringify(integration, null, 2), 'utf8');

const tsPath = join(root, 'lib', 'gcseImport', 'generatedIntegration.ts');
writeFileSync(
  tsPath,
  `/**
 * AUTO-GENERATED by scripts/generate-gcse-integration.ts — do not edit.
 * Source: data/gcse-import/*.csv
 */
import type { GcseNovaIntegration } from '@/lib/gcseImport/bridgeNova';
import generatedJson from '@/lib/gcseImport/generatedIntegration.json';

export const generatedGcse: GcseNovaIntegration = generatedJson as GcseNovaIntegration;
export default generatedGcse;
`,
  'utf8'
);

console.info('Wrote', jsonPath);
console.info('Wrote', tsPath);

function read(p: string): string {
  return readFileSync(p, 'utf8');
}
